// Code generated by tygo. DO NOT EDIT.

//////////
// source: main.go

/**
 * NodeStats is what each node-local instance exposes at /api/local-stats
 */
export interface NodeStats {
  node_id: string;
  hostname: string;
  temp_celsius?: number /* float64 */;
  containers: ContainerStats[];
}
/**
 * ContainerStats holds the resource usage snapshot for a single container.
 */
export interface ContainerStats {
  id: string;
  name: string;
  service_name: string;
  cpu_percent: number /* float64 */;
  mem_usage: number /* int64 */;
  mem_limit: number /* int64 */;
}
/**
 * NodeDetails holds the subset of swarm.Node fields used by the frontend.
 */
export interface NodeDetails {
  id: string;
  hostname: string;
  state: string;
  addr: string;
  role: string;
  is_leader: boolean;
  nano_cpus: number /* int64 */;
  memory_bytes: number /* int64 */;
}
/**
 * ServiceSummary holds the subset of swarm.Service fields used by the frontend.
 */
export interface ServiceSummary {
  id: string;
  name: string;
  image: string;
  is_global: boolean;
  replicas?: number /* uint64 */;
}
/**
 * DashboardNode is the enriched node sent to the frontend
 */
export interface DashboardNode {
  details: NodeDetails;
  temp_celsius?: number /* float64 */;
  containers: ContainerStats[];
}
